"""initial_schema

Revision ID: 8de9fe7e5df6
Revises: 
Create Date: 2026-06-11 09:56:29.561562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8de9fe7e5df6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('target_ref', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.Enum('indicates', 'uses', 'targets', 'attributed_to', 'mitigates', name='relationshiptype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.Enum('feed', 'api', 'manual', name='sourcetype'), nullable=False),
    sa.Column('tlp', sa.Enum('CLEAR', 'GREEN', 'AMBER', 'AMBER_STRICT', 'RED', name='tlplevel'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('threats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('threat_type', sa.Enum('threat_actor', 'malware', 'campaign', name='threattype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tlp', sa.Enum('CLEAR', 'GREEN', 'AMBER', 'AMBER_STRICT', 'RED', name='tlplevel'), nullable=False),
    sa.Column('stix_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stix_id')
    )
    op.create_table('indicators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('type', sa.Enum('ip', 'domain', 'url', 'md5', 'sha256', 'sha1', 'email', name='ioctype'), nullable=False),
    sa.Column('tlp', sa.Enum('CLEAR', 'GREEN', 'AMBER', 'AMBER_STRICT', 'RED', name='tlplevel'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'revoked', name='indicatorstatus'), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('value', 'type', name='uq_indicator_value_type')
    )
    op.create_index('ix_indicator_type', 'indicators', ['type'], unique=False)
    op.create_index('ix_indicator_value', 'indicators', ['value'], unique=False)
    op.create_table('attack_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('indicator_id', sa.Uuid(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('tactic', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrichments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('indicator_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_id', 'provider', name='uq_enrichment_indicator_provider')
    )
    op.create_table('sightings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('indicator_id', sa.Uuid(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sighting_seen_at', 'sightings', ['seen_at'], unique=False)
    # Ajoute 'cidr' à ioctype (maintenant que le type existe)
    op.execute("ALTER TYPE ioctype ADD VALUE IF NOT EXISTS 'cidr'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
